#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v21
# autospec commit: 94c6be0
#
Name     : perl-Future
Version  : 0.51
Release  : 39
URL      : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Future-0.51.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Future-0.51.tar.gz
Summary  : 'represent an operation awaiting completion'
Group    : Development/Tools
License  : Artistic-1.0 Artistic-1.0-Perl GPL-1.0
Requires: perl-Future-license = %{version}-%{release}
Requires: perl-Future-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
Future - represent an operation awaiting completion
SYNOPSIS
my $future = Future->new;

perform_some_operation(
on_complete => sub {
$future->done( @_ );
}
);

$future->on_ready( sub {
say "The operation is complete";
} );

%package dev
Summary: dev components for the perl-Future package.
Group: Development
Provides: perl-Future-devel = %{version}-%{release}
Requires: perl-Future = %{version}-%{release}

%description dev
dev components for the perl-Future package.


%package license
Summary: license components for the perl-Future package.
Group: Default

%description license
license components for the perl-Future package.


%package perl
Summary: perl components for the perl-Future package.
Group: Default
Requires: perl-Future = %{version}-%{release}

%description perl
perl components for the perl-Future package.


%prep
%setup -q -n Future-0.51
cd %{_builddir}/Future-0.51
pushd ..
cp -a Future-0.51 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-Future
cp %{_builddir}/Future-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-Future/ff3cb0dfd45f53bab83fc8e6480335b7afdc4bbe || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/Future.3
/usr/share/man/man3/Future::Exception.3
/usr/share/man/man3/Future::Mutex.3
/usr/share/man/man3/Future::Phrasebook.3
/usr/share/man/man3/Future::Utils.3
/usr/share/man/man3/Test::Future.3
/usr/share/man/man3/Test::Future::Deferred.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-Future/ff3cb0dfd45f53bab83fc8e6480335b7afdc4bbe

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
